dist: bionic
language: node_js
node_js:
  - 15.2.0
os: linux
before_install:
  - curl -L https://raw.githubusercontent.com/pnpm/self-installer/master/install.js | PNPM_VERSION=5.11.1 node
  - pnpm config set store-dir ~/.pnpm-store
  # - pnpm --version
  # - docker pull redislabs/redisearch
  # - docker run -p 6379:6379 redislabs/redisearch:latest
  - git clone --recursive https://github.com/RediSearch/RediSearch.git
  - cd RediSearch && make setup && make build && make run
install:
  - pnpm --recursive install
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - pnpm --recursive run test
after_success:
  - pnpm --recursive run coverage
  - cd sources/libapi && ../../cc-test-reporter format-coverage -t lcov&& cd ../..
  - cd sources/libapi && ../../cc-test-reporter after-build --exit-code $? && cd ../..
cache:
  npm: false
  directories:
    - "~/.pnpm-store"
