dist: bionic
addons:
  redis: "6.0.9"
language: node_js
node_js:
  - 15.2.1
os: linux
before_install:
  - curl -L https://raw.githubusercontent.com/pnpm/self-installer/master/install.js | PNPM_VERSION=5.12.0 node
  - pnpm config set store-dir ~/.pnpm-store
  - mkdir rs && cd rs && git clone --recursive https://github.com/RediSearch/RediSearch.git . && git checkout v2.0.2 && make build && cd $TRAVIS_BUILD_DIR
  - mkdir -p $TRAVIS_BUILD_DIR/redisearch
  - cp $TRAVIS_BUILD_DIR/rs/build/redisearch.so $TRAVIS_BUILD_DIR/redisearch
  - ls -la $TRAVIS_BUILD_DIR/redisearch
  - namei -l $TRAVIS_BUILD_DIR/redisearch/redisearch.so
  - redis-cli MODULE LOAD $TRAVIS_BUILD_DIR/redisearch/redisearch.so
  - sudo cat /var/log/redis/redis-server.log
install:
  - pnpm --recursive install
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - pnpm --recursive run test
after_success:
  - pnpm --recursive run coverage
  - cd sources/libapi && ../../cc-test-reporter format-coverage -t lcov&& cd ../..
  - cd sources/libapi && ../../cc-test-reporter after-build --exit-code $? && cd ../..
cache:
  npm: false
  directories:
    - "~/.pnpm-store"
